config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#home'

  get "about" => "about#us", as: :about
  get "terms" => "about#terms", as: :terms
  get "faq" => "about#faq", as: :faq

  get "export" => "tasks#export"

  get   "/signup" => "registrations#new"
  post  "/signup" => "registrations#create"
  get   "/signin" => "authentication#new"
  post  "/signin" => "authentication#create"
  get   "/signout" => "authentication#destroy"



end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :project
  belongs_to :role

  validates :user_id, presence: true
  validate :user_id_uniqueness_to_project, on: :create

  def user_id_uniqueness_to_project
    if user_id && Membership.where(project_id: project_id, user_id: user_id).count > 0
      errors.add(:user_id, "already a member of this project")
    end
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @memberships = @project.memberships #members on project
    @membership = @project.memberships.new #members not on project
  end

  def create
    @project = Project.find(params[:project_id])
    membership = @project.memberships.new(membership_params)
    if membership.save
      redirect_to project_memberships_path(@project)
    else
      redirect_to project_memberships_path(@project), alert: membership.errors.full_messages
    end
  end

  def update
    @project = Project.find(params[:project_id])
    membership = @project.memberships.find(params[:id])
    if membership.update(membership_params)
      redirect_to project_memberships_path, notice: "#{membership.user.full_name} was successfully updated"
    else
      redirect_to project_memberships_path(@project)
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @membership = @project.memberships.find(params[:id])
    @membership.destroy
    redirect_to project_memberships_path, notice: "#{@membership.user.full_name} was removed successfully"
  end

  private
    def membership_params
      params.require(:membership).permit(
        :project_id,
        :user_id,
        :role_id,
      )
    end

end

app/views/memberships/_error.html.erb
<% if alert %>
<div class="alert alert-danger">
  <div id="error_explanation">
    <h4><%= pluralize(alert.count, "error") %> prohibited this form from being saved:</h4>

    <ul>
      <% alert.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
</div>
<% end %>

app/views/memberships/_form.html.erb
<%= form_for [:project, @membership], html:{class:"form-inline"} do |f| %>



  <%= f.collection_select :user_id, (User.all - @project.users), :id, :full_name, {prompt: "Please select a user..."}, {class:"form-control"} %>
  <%= f.collection_select :role_id, Role.all, :id, :title, {include_blank: false}, {class:"form-control"} %>

  <%= f.submit "Add New Member", class:"btn btn-primary" %>
<% end %>

app/views/memberships/_membership.html.erb
<% if membership.user %>
  <div class="row">
    <div class="col-sm-2">
      <div class="text-center" style="line-height:2.5">
        <h4><%= link_to membership.user.full_name, user_path(membership.user) %></h4>
      </div>
    </div>
    <div class="col-sm-2">
      <div class="form-inline">
        <%= form_for [@project, membership] do |f| %>
          <%= f.collection_select :role_id, Role.all, :id, :title, {include_blank: false}, class:"form-control" %>
          <%= f.submit "Update", class:"btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-1" style="line-height:2.5">
      <%= link_to project_membership_path(params[:project_id], membership.id), method: :delete, data: { confirm: 'Are you sure?' }, class:"span", style:"color:black" do %>
      <span class="glyphicon glyphicon-remove"></span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/memberships/index.html.erb
<h1> <%= "#{@project.name}: Manage Members" %> </h1>

<ol class="breadcrumb">
  <li> <%= link_to "Projects", projects_path %> </li>
  <li> <%= link_to @project.name, project_path(@project) %> </li>
  <li class="active"> Memberships </li>
</ol>

<div class="row">
  <div class="col-sm-5">
    <%= render "error" %>
    <div class="well">
      <%= render "form" %>
    </div>
  </div>
</div>

<%= render @memberships %>