config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#home'

  get "about" => "about#us", as: :about
  get "terms" => "about#terms", as: :terms
  get "faq" => "about#faq", as: :faq

  get "export" => "tasks#export"

  get   "/signup" => "registrations#new"
  post  "/signup" => "registrations#create"
  get   "/signin" => "authentication#new"
  post  "/signin" => "authentication#create"
  get   "/signout" => "authentication#destroy"



end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project

  validates :description, presence: true
  validate :due_date_cannot_be_in_the_past, on: :create


  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "must be a future date.")
    end
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    @project = Project.find(params[:project_id])
    @tasks = @project.tasks

    if params[:filter_completed] == "true"
      @tasks = @tasks.where(completed: false)
      @active_link = "Incomplete"
    else
      @active_link = "All"
    end

    direction = {
      "desc" => :desc,
      "asc" => :asc,
      nil => :desc,
    }[params[:direction]]

    @tasks = {
      "description" => @tasks.order(description: direction),
      "due_date" => @tasks.order(due_date: direction),
      "completed" => @tasks.order(completed: direction),
      nil => @tasks
    }[params[:order_by]]
  end

  def show

  end

  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new
  end

  def edit
    @project = Project.find(params[:project_id])
    @task = @project.tasks.find(params[:id])
  end

  def create
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new(task_params)
    if @task.save
      redirect_to project_task_path(@project, @task), notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def update
    @project = Project.find(params[:project_id])
    if @task.update(task_params)
      redirect_to [@project, @task], notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to project_tasks_path, notice: 'Task was successfully destroyed.'
  end

  def export
    tasks = Task.all
    csv_data_output = []

    csv_headers = tasks.first.attributes.map {|key, v| key.to_s}
    csv_data_output.push(csv_headers.join(", "))

    tasks.each do |task|
      csv_line = task.attributes.map {|k, value| value}
      csv_data_output.push(csv_line.join(", "))
    end

    send_data csv_data_output.join("\n"), :filename => "exported_tasks.csv"
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:description, :due_date, :completed)
    end
end

app/views/tasks/_form.html.erb
<%= form_for([@project, @task], html:{class:"form-horizontal", role:"form"}) do |f| %>

  <%= render partial: "shared/errors", locals:{form_instance: @task} %>

  <div class="form-group">
    <%= f.label :description, class:"col-sm-2" %>
    <div class="col-sm-5">
      <%= f.text_field :description, class:"form-control", id:"task-description-field" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :due_date, class:"col-sm-2" %>
    <div class="col-sm-3">
      <%= f.date_field :due_date, class:"form-control" %>
    </div>
  </div>

  <% if params["action"] == "edit" %>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-5">
        <%= f.check_box :completed %>
        <%= f.label :completed %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <%= f.submit class:"btn btn-primary", id:"submit-task-action" %>

      <% if params["action"] == "new" %>
        <%= link_to 'cancel', project_tasks_path(params[:project_id]), class:"btn btn-default" %>
      <% else %>
        <%= link_to 'cancel', project_task_path(@project, @task), class:"btn btn-default" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<tr class=<%= "danger" if upcomming(task) %>>
  <td><%= task.description %></td>
  <td><%= task.completed %></td>
  <td><%= task.due_date.strftime("%m/%d/%Y") unless task.due_date.nil? %></td>
  <td>
    <div class="pull-right">
      <%= link_to 'Destroy', project_task_path(params[:project_id], task), class:"btn btn-danger", id:"destroy-task#{task.id}-action", method: :delete, data: { confirm: 'Are you sure?' } %>
      <%= link_to 'Edit', edit_project_task_path(params[:project_id], task),  class:"btn btn-info", id:"edit-task#{task.id}-action" %>
      <%= link_to 'Show', project_task_path(params[:project_id], task), class:"btn btn-success", id:"show-task#{task.id}-action" %>
    </div>
  </td>
</tr>

app/views/tasks/edit.html.erb
<header class="page-header">
  <h1>Editing task</h1>
</header>

<%= render 'form' %>

app/views/tasks/index.html.erb
<header class="page-header">

  <div class="pull-right">
    <%= link_to export_path, class:"btn btn-info span" do %>
      <span class="glyphicon glyphicon-download-alt"></span>
      <span>Download CSV</span>
    <% end %>

    <%= link_to 'New Task', new_project_task_path, class:"btn btn-info", id:"new-task-action" %>
  </div>

    <div class="pull-right" style="margin-right:10px;" >
      <div style="line-height:2.5">
      <%= link_to 'All', project_tasks_path(tasks_filter_params({"filter_completed" => nil})), class:("active-link" if @active_link == "All") %>
      |
      <%= link_to 'Incomplete', project_tasks_path(tasks_filter_params({"filter_completed" => true})), class:("active-link" if @active_link == "Incomplete") %>
      </div>
    </div>
  <h1><%= "Tasks for #{@project.name}" %></h1>
</header>

<ol class="breadcrumb">
  <li> <%= link_to "Projects", projects_path %> </li>
  <li> <%= link_to @project.name, @project %> </li>
  <li class="active"> <%= "Tasks" %> </li>
</ol>


<table class="table">
  <thead>
    <tr>
      <th><%= link_to "Description", project_tasks_path(tasks_filter_params({:order_by => "description"})) %></th>
      <th><%= link_to "Completed", project_tasks_path(tasks_filter_params({:order_by => "completed"})) %></th>
      <th><%= link_to "Due", project_tasks_path(tasks_filter_params({:order_by => "due_date"})) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <%= render @tasks %>
  </tbody>
</table>

<br>

app/views/tasks/new.html.erb
<header class="page-header">
  <h1>New task</h1>
</header>

<%= render 'form' %>

app/views/tasks/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>
<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>
<p>
  <strong>Due Date:</strong>
  <%= @task.due_date.strftime("%m/%d/%Y") unless @task.due_date.nil? %>
</p>




<%= link_to 'Edit', edit_project_task_path(params[:id],@task) %> |
<%= link_to 'Back', project_tasks_path, id:"task-index-action" %>