config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#home'

  get "about" => "about#us", as: :about
  get "terms" => "about#terms", as: :terms
  get "faq" => "about#faq", as: :faq

  get "export" => "tasks#export"

  get   "/signup" => "registrations#new"
  post  "/signup" => "registrations#create"
  get   "/signin" => "authentication#new"
  post  "/signin" => "authentication#create"
  get   "/signout" => "authentication#destroy"



end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :tasks
  has_many :memberships
  has_many :users, through: :memberships
  
  validates :name, presence: true
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def show
    @project = Project.find(params[:id])
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully deleted.'
  end



  private
    def project_params
      params.require(:project).permit(:name)
    end
end

app/views/projects/_form.html.erb
<%= form_for @project, html:{class:"form-horizontal", role:"form"} do |f| %>

  <%= render partial: "shared/errors", locals:{form_instance: @project} %>

  <div class="form-group">
    <%= f.label :name, class:"col-sm-2" %>
    <div class="col-sm-5">
      <%= f.text_field :name, class:"form-control", id:"project-name-field" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-5">
      <%= f.submit class:"btn btn-primary", id:"submit-project-action" %>
      <%= link_to 'cancel', projects_path, class:"btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<tr>
  <td>
    <%= link_to project.name, project, id:"project#{project.id}-show-action" %>
  </td>
  <td>
    <%= link_to project.tasks.count, project_tasks_path(project) %>
  </td>
</tr>

app/views/projects/edit.html.erb
<header class="page-header">
  <h1>Edit Project</h1>
</header>

<%= render "form" %>

app/views/projects/index.html.erb
<header class="page-header">
  <%= link_to "New Project", new_project_path, class:"pull-right btn btn-info", id:"new-project-action" %>
  <h1>Projects</h1>
</header>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tasks</th>
    </tr>
  </thead>

  <tbody>
    <%= render @projects %>
  </tbody>
</table>

app/views/projects/new.html.erb
<header class="page-header">
  <h1>Create Project</h1>
</header>

<%= form_for @project, html:{class:"form-horizontal", role:"form"} do |f| %>
  <% if @project.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

    <ul>
      <% @project.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, class:"col-sm-1" %>
    <div class="col-sm-4">
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-1 col-sm-4">
      <%= f.submit class:"btn btn-primary" %>
      <%= link_to 'cancel', projects_path, class:"btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/projects/show.html.erb
<header>
  <div class="pull-right">
    <%= link_to "Edit", edit_project_path(@project), class:"btn btn-info", id:"edit-project-action" %>
    <%= link_to "Delete", @project, class:"btn btn-danger", id:"delete-project-action", method: :delete, data: { confirm: 'Are you sure?' } %>
  </div>
  <h1><%= @project.name %></h1>
</header>

<ol class="breadcrumb">
  <li> <%= link_to "Projects", projects_path %> </li>
  <li class="active"> <%= @project.name %> </li>
</ol>


<%= link_to "#{pluralize(@project.tasks.count, "Task")}", project_tasks_path(@project), id:"task-index-action" %><br>
<%= link_to "#{pluralize(@project.memberships.count, "Member")}", project_memberships_path(@project) %>