config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :projects do
    resources :tasks
    resources :memberships
  end

  root 'welcome#home'

  get "about" => "about#us", as: :about
  get "terms" => "about#terms", as: :terms
  get "faq" => "about#faq", as: :faq

  get "export" => "tasks#export"

  get   "/signup" => "registrations#new"
  post  "/signup" => "registrations#create"
  get   "/signin" => "authentication#new"
  post  "/signin" => "authentication#create"
  get   "/signout" => "authentication#destroy"



end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>gCamp</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => false %>
  </head>
  <body {data-no-turbolink} >
    <div class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container-fluid">
        <div class="container">
          <div class="navbar-header">
            <%= link_to "gCamp", root_path, class:"navbar-brand" %>
          </div>

          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
              <li> <%= link_to "#{current_user.first_name} #{current_user.last_name}", user_path(current_user) %> </li>
              <li> <%= link_to "Sign Out", signout_path, id:"user-signout-action" %> </li>
            <% else %>
              <li> <%= link_to "Sign Up", signup_path, id:"user-registration-action" %> </li>
              <li> <%= link_to "Sign In", signin_path, id:"user-signin-action" %> </li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>
    <div class="container">
      <br>
      <% if flash[:notice] %>
        <div class="alert alert-success text-center">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <%= yield %>

    </div>

    <footer class="navbar navbar-fixed-bottom container">
      <hr>
      <%= link_to "About", about_path, id:"about-footer-action" %> |
      <%= link_to "Terms", terms_path, id:"terms-footer-action" %> |
      <%= link_to "FAQ", faq_path, id:"faq-footer-action" %> |
      <%= link_to "Projects", projects_path, id:"projects-footer-action" %> |
      <%= link_to "Users", users_path, id:"users-footer-action" %> |
    </footer>
  </body>
</html>